# Generated by Django 4.0.4 on 2022-06-04 16:42

from django.db import migrations, models
import django.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
        ('publication_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.SET_NUll, to='media_app.mediafile'),
        ),
    ]
