# Generated by Django 4.0.4 on 2022-06-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.ImageField(upload_to=''),
        ),
    ]
