# Generated by Django 4.0.4 on 2022-05-30 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags_app', '0003_alter_tag_options_alter_tag_title'),
        ('media_app', '0002_alter_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tags_app.tag', verbose_name='Tags'),
            preserve_default=False,
        ),
    ]
