# Generated by Django 4.0.4 on 2022-05-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0003_alter_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image_post',
            field=models.ImageField(blank=True, default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
