# Generated by Django 4.0.4 on 2022-05-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_app', '0001_initial'),
        ('media_app', '0004_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='tags_app.tags'),
        ),
    ]
